Update README.md
superchargejs/collections pull request #27
Opened 2019-10-08 09:35 UTC by gunreet03

2019-10-09 07:54 UTC, marcuspoehls requested changes
@gunreet03 Hey Gunreet, thank you for the PR! It's a good addition.

Can you please have a look at this minor refinement?

2019-10-09 07:54 UTC, marcuspoehls commented on README.md
> +You can directly await the result for methods returning a definite value. The function returns a new instance of the collection without altering the original input array.
I'd love to keep the colon at the end :)
Can you please add it again?

```suggestion
You can directly await the result for methods returning a definite value. The function returns a new instance of the collection without altering the original input array:
```

2019-10-09 08:06 UTC, gunreet03 commented
Sure I'll. Thank you for taking out time to review.

On Wed, Oct 9, 2019, 13:24 Marcus Poehls <notifications@github.com> wrote:

> *@marcuspoehls* requested changes on this pull request.
>
> @gunreet03 <https://github.com/gunreet03> Hey Gunreet, thank you for the
> PR! It's a good addition.
>
> Can you please have a look at this minor refinement?
> ------------------------------
>
> In README.md
> <https://github.com/superchargejs/collections/pull/27#discussion_r332873350>
> :
>
> > @@ -67,7 +67,7 @@ await Collect(
>
>
>
>  **Notice:** when chaining methods like `map` or `filter`, you'll receive a collection instance in return. You must actively end the call chain using the `.all()` method to process the collection pipeline and retrieve the final result.
>
>
>
> -You can directly await the result for methods returning a definite value:
>
> +You can directly await the result for methods returning a definite value. The function returns a new instance of the collection without altering the original input array.
>
>
> I'd love to keep the colon at the end :)
> Can you please add it again?
> ⬇️ Suggested change
>
> -You can directly await the result for methods returning a definite value. The function returns a new instance of the collection without altering the original input array.
>
> +You can directly await the result for methods returning a definite value. The function returns a new instance of the collection without altering the original input array:
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/superchargejs/collections/pull/27?email_source=notifications&email_token=ALJJDZTUYQO456E6OMR2VGLQNWE2TA5CNFSM4I6PJ6VKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCHK5UCI#pullrequestreview-299227657>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALJJDZSUV5J26SJ5UDAPSDDQNWE2TANCNFSM4I6PJ6VA>
> .
>

2019-10-22 13:23 UTC, marcuspoehls commented
@gunreet03 Hey Gunreet, any chance to refine this PR?

2019-10-24 04:20 UTC, closed without merging